@startuml
actor User
entity Main_activity
entity Team_Activity
participant FetchHeartRates
participant AWSDatabaseHelper
database AWSDatabase

... Team Monitoring Sequence ...

User --> Main_activity : Open App
activate Main_activity
Main_activity -> Team_Activity : GoToTeamActivity
deactivate Main_activity
activate Team_Activity
group Updates at 1S/10s
FetchHeartRates -> AWSDatabaseHelper : Query HeartRates
activate AWSDatabaseHelper
AWSDatabaseHelper -> Team_Activity : ArrayList<HeartRatesDO> hrList
deactivate AWSDatabaseHelper
Team_Activity -> Team_Activity : Update ListView
end

User --> Team_Activity : Click User in ListView
group Updates at 1S/10s
Team_Activity -> Team_Activity : Update Graphs and TextViews
end
... Monitoring ...
@enduml